### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by sw4p** [edgeimpulse/example-portenta-lorawan#2]
On using a new model (a simple image classification impulse) I am getting this linker error

\PORTENTA_H7_M7/linker_script.ld:106 cannot move location counter backwards (from 240835c8 to 2407fc00)
collect2.exe: error: ld returned 1 exit status

I have tried updating the mbed core but could not pinpoint the issue.

any tip?

**Comment by hpssjellis** [comment]
possibly out of RAM   https://arduino.stackexchange.com/questions/81534/ld-exelinker-script-ld138-cannot-move-location-counter-backwards-arduinofft


I have had the ```collect2.exe: error: ld returned 1 exit status``` can't remember the fix. What size image impulse are you trying

**Comment by sw4p** [comment]
That's what I also thought but the model I am using consumes only 296.8KB of RAM whereas Portenta has 8MB of it.
![image](https://user-images.githubusercontent.com/20498418/126008263-f00709f9-8879-4389-9306-cb15f83fb565.png)

**Comment by sw4p** [comment]
The image size I am using is 96x96. In the readme, it is mentioned to use 64x64. Generating a new model with reduced image size.

**Comment by hpssjellis** [comment]
96x96 is small for the Portenta. Are you using GRAYSCALE or RGB, should really mater. Are you using the Vision Shields? What arduino source code. I don't think Edge Impulse have example vision code out yet for the Portenta. Also are you using th LoRaWan in europe or US as I think things are different. Want to put this on the forum as more people may have a look at it.

**Comment by sw4p** [comment]
I was using RGB but just now I changed it to GRAYSCALE. I am using the LoRaWan vision shield but not using the LoRaWan feature and have removed it from the code.
You are right! Edge Impulse does not have an officially released example vision code that is why I am using the code provided by @janjongboom in this repo.

**Comment by hpssjellis** [comment]
OK, I haven't used it for a while, but here is my vision shield code. Perhaps have a look and see if it helps with debugging

https://github.com/hpssjellis/my-examples-of-edge-impulse/blob/main/PortentaVisionShield/port-vis-10-led.ino

**Comment by sw4p** [comment]
Thank you @hpssjellis! Apart from this what is a better way to run an edge impulse model on a Portenta board? via openmv?

**Comment by hpssjellis** [comment]
OpenMV is awesome, I just stay away from it since I can't use both cores with it yet.  Here is a video I made of how to use it.   https://www.youtube.com/watch?v=WexgCijWfvY&list=PL57Dnr1H_egsQPnEObWHPhK1Q4g_IDWcR&index=3

**Comment by sw4p** [comment]
brilliant! Cheers.
